version: '3'
services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: RecommenderDB
      MYSQL_USER: bold_user
      MYSQL_PASSWORD: BOLD+USER*PW*1205*
      MYSQL_ROOT_PASSWORD: PW*BBR!ROOT
    networks:
      - springmysql-net
    volumes:
      - "./BBRecommenderDB/.data/db:/var/lib/mysql"
      

  backend:
    # build: ./BBRecommenderBE
    image: baetenjens/beboldrecommender:backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/RecommenderDB
      SPRING_DATASOURCE_USERNAME: bold_user
      SPRING_DATASOURCE_PASSWORD: BOLD+USER*PW*1205*
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
   
  frontend:
    # build: ./BBRecommenderFE
    image: baetenjens/beboldrecommender:frontend
    ports:
      - "81:81"
    depends_on:
      - backend
    networks:
      - springmysql-net

volumes:
  db-data:

networks:
  springmysql-net:
    driver: bridge 
