FROM openjdk:17-jdk-alpine
RUN addgroup --system bebold
RUN adduser --system -G bebold rudy
USER rudy
ARG JAR_FILE=target/*.jar
ADD ${JAR_FILE} app.jar

# Copy the current directory contents into the container at /app
COPY ./target/bbrecommenderbe-0.0.1.jar app.jar

EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app.jar"]

